BOARD_WIDTH = 8
MIN_BOARD_WIDTH = 7  # shouldn't be changed
TOP_N_AMOUNT = 5
# MINMAX_DEPTH = 6
# MINMAX_N_DEPTH = 6
MINMAX_DIFFICULTY_MEDIUM = [3, 2]
MINMAX_DIFFICULTY_HARD = [6, 6]
DEPTH_TO_CHECK = 16
